In [5]:
import pandas as pd
import numpy as np
from sklessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics imporearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Step 1: Import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preproct accuracy_score, confusion_matrix, classification_report

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [6]:
# Step 2: Load Data
# Replace 'your_dataset.csv' with your actual CSV file path
df = pd.read_csv('C:/Users/hp/OneDrive/Desktop/DataSet1_final.csv')

# Step 3: Preprocess Data
# Handle missing values if any
# df.fillna(method='ffill', inplace=True)

In [7]:
# # Encode categorical features if any
# label_encoders = {}
# for column in df.select_dtypes(include=['object']).columns:
#     label_encoders[column] = LabelEncoder()
# df[column] = label_encoders[column].fit_transform(df[column])

In [8]:
# # Split the dataset into features and target variable
# # Replace 'target_column' with your actual target column name


# X = df.drop('LeadershipQuality', axis=1)


# y = df['LeadershipQuality']

In [9]:

# # Split the dataset into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
# Drop irrelevant columns
df = df.drop(['Name', 'Student Id', 'Timestamp'], axis=1, errors='ignore')  # Use actual column names

# Label encode categorical columns (e.g., Gender, Branch)
label_encoders = {}
for column in df.select_dtypes(include='object').columns:
    if column != 'LeadershipQuality':
        le = LabelEncoder()
        df[column] = le.fit_transform(df[column])
        label_encoders[column] = le

# Encode the target column
df['LeadershipQuality'] = LabelEncoder().fit_transform(df['LeadershipQuality'])

# Split features and target
X = df.drop('LeadershipQuality', axis=1)
y = df['LeadershipQuality']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [11]:
# Step 4: Train Model
model = SVC()
model.fit(X_train, y_train)

# Step 5: Make Predictions
y_pred = model.predict(X_test)

In [12]:

# Step 6: Evaluate Model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.9469026548672567
Confusion Matrix:
[[75  0]
 [ 6 32]]
Classification Report:
              precision    recall  f1-score   support

           0       0.93      1.00      0.96        75
           1       1.00      0.84      0.91        38

    accuracy                           0.95       113
   macro avg       0.96      0.92      0.94       113
weighted avg       0.95      0.95      0.95       113



In [13]:
model =  LogisticRegression()
model.fit(X_train, y_train)

# Step 5: Make Predictions
y_pred = model.predict(X_test)

In [14]:
# Step 6: Evaluate Model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.9911504424778761
Confusion Matrix:
[[75  0]
 [ 1 37]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        75
           1       1.00      0.97      0.99        38

    accuracy                           0.99       113
   macro avg       0.99      0.99      0.99       113
weighted avg       0.99      0.99      0.99       113



In [15]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.9911504424778761
Confusion Matrix:
[[75  0]
 [ 1 37]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        75
           1       1.00      0.97      0.99        38

    accuracy                           0.99       113
   macro avg       0.99      0.99      0.99       113
weighted avg       0.99      0.99      0.99       113



In [16]:
# Step 4: Train Model
model = GaussianNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [17]:
# Step 4: Train Model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Step 5: Make Predictions
y_pred = model.predict(X_test)

In [18]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f'Accuracy: {accuracy}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)

Accuracy: 0.8938053097345132
Confusion Matrix:
[[70  5]
 [ 7 31]]
Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.93      0.92        75
           1       0.86      0.82      0.84        38

    accuracy                           0.89       113
   macro avg       0.89      0.87      0.88       113
weighted avg       0.89      0.89      0.89       113

